XRandR Improvements
sharplispers/clx pull request #193
Opened 2022-07-02 13:04 UTC by scymtym

* Tab, whitespace, comment  cleanup

* Separate package for the extension

* Fix and complete various things

  * Notify events

  * Mask and type definition macros

  * Accessor definitions for `panning`, `mode-info`, etc

  * A few incomplete definitions of CRTC and output functions

2022-07-02 13:42 UTC, JMC-design commented
Does the rr-panning-put really still not work?  I was kinda hoping to see what the issue was with that.

2022-07-03 12:21 UTC, dkochmanski commented on extensions/randr.lisp
> +  )
s/or/member/?

2022-07-03 12:33 UTC, dkochmanski requested changes
only minor remarks

2022-07-03 12:33 UTC, dkochmanski commented on extensions/randr.lisp
> +  #+TODO (let ((seq          (if filter-parameters (coerce filter-parameters 'vector) nil ))
please use `#+(or)` or comment out the block.

2022-07-03 12:33 UTC, dkochmanski commented on extensions/randr.lisp
> +  "FIXME:Transform may be a list or vector of length 9.  ?perhaps allow length 6?"
this is a comment, not a documentation string - please make it so

2022-07-03 12:33 UTC, dkochmanski commented on extensions/randr.lisp
> +                                        ;((sequence :format card32) seq)
fix indentation and uniform comment

2022-07-03 15:27 UTC, scymtym commented
Sorry, this was meant to be a draft, not ready for review. Since I promised @JMC-design to let them have a look.

2022-07-03 15:27 UTC, dkochmanski commented
OK, thanks. I've converted PR to draft.

2022-08-02 07:47 UTC, scymtym commented
One issue I couldn't come to a decision on: should the synchronous operations that receive a success or failure indication in the reply just return that value or signal a condition on failure (example: `get-output-info` returns either `:success` or `:failure` as the first return value). I lean towards just returning the value and leave the construction of convenience layers to clients but that does, of course, make the base interface less convenient.

Similarly, some operations return "meta data" in the form of timestamps and "configuration timestamps" along with the primary data. The order of return values is currently mostly modeled after the order of fields in the respective XRandR reply structure. However, it might make sense to return the meta data values as the final values since they seem to not always be needed.

2022-08-08 06:42 UTC, dkochmanski requested changes

2022-08-08 06:42 UTC, dkochmanski commented on extensions/randr.lisp
> -(in-package :xlib)
this change seems to be against rules established in the codebase, all extensions are defined in the xlib package. macros also assume that everything is defined in the xlib package. In light of that please define the extension in the same package with the rr prefix like it was before. I agree that this is not optimal.

2022-08-08 06:42 UTC, dkochmanski commented on extensions/randr.lisp
> +           )
please elaborate in the commit message why these events are commented out and elaborate what do you mean by "fix various notify events".

2022-08-08 06:42 UTC, dkochmanski commented on extensions/randr.lisp
> +  (when filter-parameters (error "Filter parameters are not currently supported"))
please break a line here

2023-01-11 10:09 UTC, merged